### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by ffMathy** [pdyck/hearthstone-db#10]
Title speaks for itself. Will the repository be updated as new cards come up? I found some that are missing.

Would it make sense to write a crawler for this kind of stuff so maintenance would be easy?

**Comment by pdyck** [comment]
I have a few scripts that pull the data from a wiki and standardize it after that. In the near future I would like to add a comprehensive script to the repository, probably when all the Whispers cards are released.
afaik all _released_ cards are included. If you think that something is missing you can submit a pull request with a fix

**Comment by ffMathy** [comment]
Thanks. And thanks for this wonderful repository.

**Comment by pdyck** [comment]
✌
