### ISSUE TITLE
`npm` module has not been updated

### ISSUE THREAD

**Issue by gnerkus** [pdyck/hearthstone-db#11]
The `hearthstone-db` module on npmjs.com has not been updated; the LOE and WOTG expansions have not been added yet.

I'd like to help with it if that's possible.

**Comment by pdyck** [comment]
Do you know how to do that? I bumped the version number in package.json but it's still the old version on npm...

**Comment by gnerkus** [comment]
I think you need to publish the package again. https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package

**Comment by pdyck** [comment]
Thanks, I am sorry that it took so long.
