### ISSUE TITLE
In all-collectables, it does not include nerfs

### ISSUE THREAD

**Issue by travers-bryan** [pdyck/hearthstone-db#15]
Molten Giant is set to 20 mana, Big Game Hunter is at 3 mana etc...
Call of the wild is at 8 mana, Rockbighter weapon is get to 1 mana etc...

**Comment by pdyck** [comment]
Card nerfs/changes haven't been implemented since Patch 3.2.0.10604 (2015-10-20) in all files of the repository. I am going to commit the changes today.

**Comment by pdyck** [comment]
Fixed
