### ISSUE TITLE
type / category

### ISSUE THREAD

**Issue by kdannies** [pdyck/hearthstone-db#16]
Wanted to write a little tool for myself to use. Came across this data base of cards ( thank you for saving me a bunch of work with this). I came across an onconsistency: Up to wrath of the old gods, there was a "type", which then seemngly was replaced by "category". any reason for it?

**Comment by pdyck** [comment]
Thanks for the heads up!

Imo type doesn't define the attribute well enough. I must have forgotten to change the old data. I will submit the changes later today! :)

**Comment by pdyck** [comment]
Resolved with commit 223dab27d3e6fb6ad73dfea7aa2d0e0fe69b8d37
