### ISSUE TITLE
all-collectibles.json missing promo cards

### ISSUE THREAD

**Issue by Freezard** [pdyck/hearthstone-db#17]
Elite Tauren Chieftain and Gelbin Mekkatorque from the Promo set are missing. Might be missing in other files as well, haven't checked.

Also a few cards start their description with "[x]" for some reason (like Arcane Giant), not sure if intended?

**Comment by pdyck** [comment]
There are some cards that are missing, like Tavern Brawl exclusive cards etc. I try to include all playable cards, so I will include **Elite Tauren Chieftain** and **Gelbin Mekkatorque**. Please submit another issue, if you should find any other missing cards!

The descriptions starting with "[x]" is definitely a bug. I will submit a fix later.

Thank you for reporting the bugs!
