### ISSUE TITLE
<b> tags in descriptions

### ISSUE THREAD

**Issue by Freezard** [pdyck/hearthstone-db#19]
I noticed some cards have `<b>` tags in their descriptions, for keywords like battlecry, while many others doesn't. Only expert and gadgetzan cards seems to have them. Not sure if they should be included or not, but it's a problem with consistency.

**Comment by pdyck** [comment]
I already went over the data and removed some `<b>` tags but I seem to have missed a few. If you want to you can submit another pull request. If not, I will fix the issue soon.
Thank you for your help!
