### ISSUE TITLE
Experiencing an error with the description of the card.

### ISSUE THREAD

**Issue by pringon** [pdyck/hearthstone-db#6]
If i try to filter through the json file by checking the description with and indexOf it says Uncaught TypeError: Cannot read property 'indexOf' of undefined, tried using some other functions on the description and it gives me the same error.

**Comment by pdyck** [comment]
On which object are you using this function? What are you trying to find? Maybe you use it on a string and you have to parse it to JSON first.

**Comment by pringon** [comment]
pringon.me/index.js this is the code that i am using(i comented that part since it made the code stop working when i pressed the  button).I tried taking out the replace and toLowerCase but it is still not working

**Comment by pdyck** [comment]
You could use a loop to go through the data to find what you are looking for instead of using indexOf(). You should also start learning javascript instead of using jquery for everything.
